apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-nodejs-demo
  labels:
    app: ecsdemo-nodejs
  namespace: eks-nodejs-demo
spec:
  replicas: 10
  selector:
    matchLabels:
      app: eks-nodejs-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eks-nodejs-demo
    spec:
      containers:
      - image: brentley/ecsdemo-nodejs:latest
        imagePullPolicy: Always
        name: eks-nodejs-demo
        ports:
        - containerPort: 3000
          protocol: TCP
