apiVersion: v1
kind: Service
metadata:
  name: ecsdemo-nodejs
  namespace: eks-nodejs-demo
spec:
  selector:
    app: eks-nodejs-demo
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000

